project:
  type: website

website:
  title: "Josh Cowley"
  site-url: https://josh.quarto.pub/
  navbar:
    left:
      - icon: github
        href: https://github.com/nclJoshCowley
      - icon: envelope
        href: mailto:j.cowley1@ncl.ac.uk
      - icon: linkedin
        href: https://www.linkedin.com/in/josh-cowley-28a3a7194/
    right:
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css

filters:
  - code-filename

