project:
  type: website

website:
  title: "Josh Cowley"
  navbar:
    left:
      - icon: github
        href: https://github.com/nclJoshCowley
      - icon: linkedin
        href: https://www.linkedin.com/in/josh-cowley-28a3a7194/
    right:
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css



