#' Simulate Logistic Regression Data
#'
#' Simulates binary outcomes from a logistic regression model with one
#' continuous predictor drawn from a uniform distribution on [-1.5, 1.5].
#'
#' @param n Integer. Sample size.
#' @param intercept Numeric. Intercept of the linear predictor.
#' @param slope Numeric. Slope of the linear predictor.
#'
#' @return A tibble with columns:
#' \itemize{
#'   \item `probability` — true success probability,
#'   \item `event` — simulated binary outcome (0/1),
#'   \item `x` — simulated predictor values.
#' }
#'
#' @note Documentation generated by ChatGPT.
simulate_logistic <- function(n, intercept, slope) {
  x <- stats::runif(n, min = -0.5, max = 0.5)

  # Linear predictor
  eta <- intercept + slope * x

  # Logistic transformation
  prob <- 1 / (1 + exp(-eta))

  # Observed event (Y/N)
  event <- rbinom(n = n, size = 1, prob = prob)

  tibble::tibble(probability = prob, event = event, x = x)
}
